# Generated by Django 5.1.7 on 2025-03-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_disease_description_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSymptoms',
        ),
    ]
