# Generated by Django 5.1.7 on 2025-03-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_delete_usersymptoms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
